apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  # Dışarıdan erişim için NodePort
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081