apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  type: ClusterIP
  selector:
    app: consumer
  ports:
    - name: dummy
      port: 80
      targetPort: 8080