apiVersion: v1
kind: Service
metadata:
  name: kafka2
  labels:
    app: kafka2
spec:
  type: ClusterIP
  selector:
    app: kafka2
  ports:
    - name: controller
      port: 29093
      targetPort: 29093
    - name: plaintext
      port: 29094
      targetPort: 29094
    - name: host
      port: 9093
      targetPort: 9093
    - name: jmx
      port: 5556
      targetPort: 5556