apiVersion: v1
kind: Service
metadata:
  name: kafka3
  labels:
    app: kafka3
spec:
  type: ClusterIP
  selector:
    app: kafka3
  ports:
    - name: controller
      port: 29093
      targetPort: 29093
    - name: plaintext
      port: 29096
      targetPort: 29096
    - name: host
      port: 9094
      targetPort: 9094
    - name: jmx
      port: 5556
      targetPort: 5556