apiVersion: v1
kind: Service
metadata:
  name: kafka1
  labels:
    app: kafka1
spec:
  type: ClusterIP
  selector:
    app: kafka1
  ports:
    - name: controller
      port: 29093
      targetPort: 29093
    - name: plaintext
      port: 29092
      targetPort: 29092
    - name: host
      port: 9092
      targetPort: 9092
    - name: jmx
      port: 5556
      targetPort: 5556