apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: producer
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
    - name: dummy
      port: 80
      targetPort: 8080