apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kafka-jmx'
        static_configs:
          - targets:
            - 'kafka1:5556'
            - 'kafka2:5556'
            - 'kafka3:5556'