FROM confluentinc/cp-kafka:7.5.1
 
USER root
RUN yum -y update && yum -y install curl
RUN mkdir -p /opt && chmod 777 /opt
 
ARG JMX_EXPORTER_VERSION=0.17.2
RUN curl -sSL https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${JMX_EXPORTER_VERSION}/jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar \
    -o /opt/jmx_prometheus_javaagent.jar
 
COPY jmx_exporter_config.yaml /opt/jmx_exporter_config.yaml
 
ENV KAFKA_OPTS="-javaagent:/opt/jmx_prometheus_javaagent.jar=5556:/opt/jmx_exporter_config.yaml"
 
EXPOSE 5556