# Node.js 16 sürümünü içeren resmi Docker imajını kullan
FROM node:16

# Çalışma dizinini '/app' olarak ayarla
WORKDIR /app

# package.json ve package-lock.json dosyalarını konteynerin içine kopyala
COPY package*.json ./

# Bağımlılıkları yükle
RUN npm install

# Proje dosyalarını konteynerin içine kopyala
COPY . .

# 8080 portunu dışarıya aç
EXPOSE 8080

# 'api.js' dosyasını çalıştırarak Node.js uygulamasını başlat
CMD [ "node", "api.js" ]
